# Generated by Django 4.1.4 on 2022-12-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
