# Generated by Django 4.1.4 on 2022-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_description_alter_blog_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="blog",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
